# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('artid', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('title', models.CharField(max_length=18)),
                ('conten', models.TextField()),
                ('author', models.CharField(max_length=18)),
                ('coverimgs', models.ImageField(upload_to='')),
                ('numcilck', models.IntegerField()),
                ('abstract', models.CharField(max_length=100, null=True)),
                ('classify', models.CharField(max_length=18)),
                ('datime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clsslist',
            fields=[
                ('clasid', models.AutoField(primary_key=True, serialize=False)),
                ('clasname', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=18)),
                ('pswd', models.CharField(max_length=18)),
                ('sex', models.CharField(max_length=4, null=True)),
                ('age', models.IntegerField(null=True)),
                ('identity', models.CharField(max_length=6, null=True)),
            ],
        ),
    ]
