# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_plannedtask_staktime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedtask',
            name='staktime',
            field=models.DateField(),
        ),
    ]
