# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_auto_20180111_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.CharField(default='627656470@qq.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='15179601349', max_length=11),
            preserve_default=False,
        ),
    ]
