# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_auto_20180114_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='MYLabel',
            fields=[
                ('LabelID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('conten', models.CharField(max_length=200)),
                ('settime', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.User')),
            ],
        ),
    ]
