# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_mylabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='porjectProc',
            fields=[
                ('ProcID', models.AutoField(primary_key=True, serialize=False)),
                ('conten', models.CharField(max_length=300)),
                ('setitme', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='projectfile',
            fields=[
                ('pjectfileID', models.AutoField(primary_key=True, serialize=False)),
                ('filepath', models.CharField(max_length=100)),
                ('settime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='projectplan',
            fields=[
                ('prijectpID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('conten', models.CharField(max_length=300)),
                ('degree', models.IntegerField()),
                ('settime', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='projectfile',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.projectplan'),
        ),
        migrations.AddField(
            model_name='porjectproc',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.projectplan'),
        ),
    ]
