# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_auto_20180119_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplan',
            name='urlgithub',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
