# Generated by Django 2.0.1 on 2018-01-20 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_projectfile_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='subfile',
            fields=[
                ('fileid', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=30)),
                ('settime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subproject',
            fields=[
                ('SubID', models.AutoField(primary_key=True, serialize=False)),
                ('subtitle', models.CharField(max_length=100)),
                ('describe', models.CharField(max_length=200)),
                ('completenum', models.IntegerField()),
                ('cltype', models.CharField(max_length=15)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.projectplan')),
            ],
        ),
        migrations.AlterField(
            model_name='porjectproc',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Subproject'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='filename',
            field=models.CharField(max_length=25),
        ),
        migrations.AddField(
            model_name='subfile',
            name='subproID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Subproject'),
        ),
    ]
