# Generated by Django 2.0.1 on 2018-01-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_auto_20180121_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porjectproc',
            name='conten',
            field=models.TextField(),
        ),
    ]
