# Generated by Django 2.0.1 on 2018-01-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_auto_20180128_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_info',
            name='describe',
            field=models.CharField(default='sdsds', max_length=200),
            preserve_default=False,
        ),
    ]
