# Generated by Django 2.0.1 on 2018-02-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_server_info_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_info',
            name='sertype',
            field=models.CharField(default='index', max_length=5),
            preserve_default=False,
        ),
    ]
