# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filelis',
            fields=[
                ('Filesid', models.AutoField(primary_key=True, serialize=False)),
                ('Filepath', models.CharField(max_length=100)),
                ('FileName', models.CharField(max_length=30)),
                ('FileSize', models.IntegerField()),
                ('Filetype', models.CharField(max_length=8)),
                ('FileFolder', models.CharField(max_length=15, null=True)),
                ('datime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imgs',
            fields=[
                ('imgid', models.AutoField(primary_key=True, serialize=False)),
                ('imgpath', models.CharField(max_length=100)),
                ('imgName', models.CharField(max_length=30)),
                ('imgSize', models.IntegerField()),
                ('imgtype', models.CharField(max_length=8)),
            ],
        ),
    ]
