# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_filelis_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelis',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imgs',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.User'),
            preserve_default=False,
        ),
    ]
