# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20180109_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedtask',
            name='remndtime',
        ),
        migrations.AddField(
            model_name='plannedtask',
            name='endtime',
            field=models.DateField(default='2018-1-9'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannedtask',
            name='strattime',
            field=models.DateField(default='2018-1-9'),
            preserve_default=False,
        ),
    ]
