# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20180109_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedtask',
            name='Interval',
            field=models.CharField(max_length=20),
        ),
    ]
