# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20180109_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedtask',
            name='staktime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
