# Generated by Django 2.0.1 on 2018-01-20 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_auto_20180120_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='settime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
