# Generated by Django 2.0.1 on 2018-01-28 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_auto_20180125_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='cpu_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpurate', models.FloatField()),
                ('procees_ls', models.IntegerField()),
                ('procees_total', models.IntegerField()),
                ('settime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Harddisk_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disk_rate', models.FloatField()),
                ('disk_total', models.FloatField()),
                ('disk_used', models.FloatField()),
                ('disk_Surplus', models.FloatField()),
                ('settime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='memory_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('memoryrate', models.FloatField()),
                ('Available', models.FloatField()),
                ('memory_total', models.FloatField()),
                ('memory_used', models.FloatField()),
                ('settime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='server_info',
            fields=[
                ('serverid', models.AutoField(primary_key=True, serialize=False)),
                ('servername', models.CharField(max_length=25)),
                ('key', models.CharField(max_length=30)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='memory_info',
            name='serverid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.server_info'),
        ),
        migrations.AddField(
            model_name='harddisk_info',
            name='serverid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.server_info'),
        ),
        migrations.AddField(
            model_name='cpu_info',
            name='serverid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.server_info'),
        ),
    ]
